apiVersion: v1
kind: Service
metadata:
  name: {{ include "prax.fullname" . }}-teamwork
  namespace: {{ include "prax.namespace" . }}
  labels:
    {{- include "prax.componentLabels" (dict "component" "teamwork" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "prax.componentSelectorLabels" (dict "component" "teamwork" "context" $) | nindent 4 }}
