"""Office document export tools — create .pptx, .xlsx, and .pdf files.

These tools generate office documents from structured data and save them
to the user's workspace.  Any spoke can use them (content, knowledge, etc.).

Dependencies (must be in pyproject.toml):
- python-pptx  — PowerPoint generation
- openpyxl     — Excel spreadsheet generation
- fpdf2        — PDF generation (lightweight, pure Python)
"""
from __future__ import annotations

import json
import logging
import re
from io import BytesIO

from langchain_core.tools import tool

from prax.agent.user_context import current_user_id
from prax.services import workspace_service

logger = logging.getLogger(__name__)


def _get_user_id() -> str:
    uid = current_user_id.get()
    if not uid:
        return "unknown"
    return uid


def _slugify(text: str) -> str:
    """Turn a title into a safe filename (no extension)."""
    slug = re.sub(r"[^\w\s-]", "", text.lower().strip())
    slug = re.sub(r"[\s_]+", "_", slug)
    return slug[:80] or "document"


# ---------------------------------------------------------------------------
# PowerPoint (.pptx)
# ---------------------------------------------------------------------------

@tool
def create_presentation(title: str, slides_json: str) -> str:
    """Create a PowerPoint presentation (.pptx) from structured slide data.

    Args:
        title: Presentation title (used as filename and title slide).
        slides_json: JSON array of slide objects. Each slide has:
            - "title": slide title
            - "content": bullet points as a list of strings
            - "notes": optional speaker notes
            - "layout": optional ("title", "bullets", "two_column", "blank")

            Example: [
                {"title": "Introduction", "content": ["Point 1", "Point 2"]},
                {"title": "Analysis", "content": ["Finding A", "Finding B"], "notes": "Emphasize finding B"}
            ]

    Returns: Path to the saved .pptx file in the workspace.
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        return (
            "python-pptx is not installed. Add it to pyproject.toml: "
            "uv add python-pptx"
        )

    try:
        slides = json.loads(slides_json)
    except json.JSONDecodeError as exc:
        return f"Invalid slides_json: {exc}"

    if not isinstance(slides, list):
        return "slides_json must be a JSON array of slide objects."

    try:
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # Title slide
        title_layout = prs.slide_layouts[0]  # Title Slide layout
        slide = prs.slides.add_slide(title_layout)
        slide.shapes.title.text = title
        if slide.placeholders[1]:
            slide.placeholders[1].text = f"Generated by {_get_user_id()}"

        # Content slides
        for i, slide_data in enumerate(slides):
            slide_title = slide_data.get("title", f"Slide {i + 1}")
            content = slide_data.get("content", [])
            notes = slide_data.get("notes", "")
            layout = slide_data.get("layout", "bullets")

            if layout == "title":
                sl = prs.slides.add_slide(prs.slide_layouts[0])
                sl.shapes.title.text = slide_title
            elif layout == "blank":
                sl = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
            elif layout == "two_column":
                # Use a content slide and split content into two text boxes
                sl = prs.slides.add_slide(prs.slide_layouts[1])
                sl.shapes.title.text = slide_title
                if content and sl.placeholders.get(1):
                    mid = len(content) // 2
                    left_text = "\n".join(f"\u2022 {c}" for c in content[:mid])
                    right_text = "\n".join(f"\u2022 {c}" for c in content[mid:])
                    sl.placeholders[1].text = f"{left_text}\n\n{right_text}"
            else:
                # Default: bullets layout
                sl = prs.slides.add_slide(prs.slide_layouts[1])
                sl.shapes.title.text = slide_title
                if content and sl.placeholders.get(1):
                    tf = sl.placeholders[1].text_frame
                    tf.clear()
                    for j, bullet in enumerate(content):
                        if j == 0:
                            tf.text = str(bullet)
                        else:
                            p = tf.add_paragraph()
                            p.text = str(bullet)
                            p.font.size = Pt(18)

            # Speaker notes
            if notes:
                sl.notes_slide.notes_text_frame.text = notes

        # Save to bytes buffer then to workspace
        buf = BytesIO()
        prs.save(buf)
        buf.seek(0)

        filename = f"{_slugify(title)}.pptx"
        uid = _get_user_id()
        path = workspace_service.save_file(uid, filename, buf.read())
        logger.info("Created presentation: %s (%d slides)", path, len(slides))
        return f"Presentation saved: {path} ({len(slides) + 1} slides including title)"

    except Exception as exc:
        logger.warning("Failed to create presentation: %s", exc, exc_info=True)
        return f"Failed to create presentation: {exc}"


# ---------------------------------------------------------------------------
# Excel (.xlsx)
# ---------------------------------------------------------------------------

@tool
def create_spreadsheet(title: str, sheets_json: str) -> str:
    """Create an Excel spreadsheet (.xlsx) from structured data.

    Args:
        title: Spreadsheet title (used as filename).
        sheets_json: JSON array of sheet objects. Each sheet has:
            - "name": sheet tab name
            - "headers": list of column headers
            - "rows": list of lists (each inner list is a row)
            - "column_widths": optional list of widths

            Example: [
                {"name": "Sales", "headers": ["Month", "Revenue"], "rows": [["Jan", 1000], ["Feb", 1500]]}
            ]

    Returns: Path to the saved .xlsx file in the workspace.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font
        from openpyxl.utils import get_column_letter
    except ImportError:
        return (
            "openpyxl is not installed. Add it to pyproject.toml: "
            "uv add openpyxl"
        )

    try:
        sheets = json.loads(sheets_json)
    except json.JSONDecodeError as exc:
        return f"Invalid sheets_json: {exc}"

    if not isinstance(sheets, list):
        return "sheets_json must be a JSON array of sheet objects."

    try:
        wb = Workbook()
        # Remove the default sheet if we have data
        if sheets:
            wb.remove(wb.active)

        bold_font = Font(bold=True)

        for sheet_data in sheets:
            sheet_name = sheet_data.get("name", "Sheet")[:31]  # Excel max 31 chars
            headers = sheet_data.get("headers", [])
            rows = sheet_data.get("rows", [])
            column_widths = sheet_data.get("column_widths", [])

            ws = wb.create_sheet(title=sheet_name)

            # Write headers with bold formatting
            for col_idx, header in enumerate(headers, 1):
                cell = ws.cell(row=1, column=col_idx, value=str(header))
                cell.font = bold_font

            # Write data rows
            for row_idx, row in enumerate(rows, 2):
                for col_idx, value in enumerate(row, 1):
                    ws.cell(row=row_idx, column=col_idx, value=value)

            # Column widths — use provided or auto-calculate
            if column_widths:
                for col_idx, width in enumerate(column_widths, 1):
                    ws.column_dimensions[get_column_letter(col_idx)].width = width
            else:
                # Auto-size: measure max content length per column
                for col_idx in range(1, len(headers) + 1):
                    max_len = len(str(headers[col_idx - 1])) if col_idx <= len(headers) else 8
                    for row in rows:
                        if col_idx - 1 < len(row):
                            cell_len = len(str(row[col_idx - 1]))
                            if cell_len > max_len:
                                max_len = cell_len
                    # Add padding, cap at 50
                    ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 3, 50)

        # If no sheets were added, create at least one
        if not sheets:
            wb.create_sheet(title="Sheet1")

        # Save to bytes buffer then to workspace
        buf = BytesIO()
        wb.save(buf)
        buf.seek(0)

        filename = f"{_slugify(title)}.xlsx"
        uid = _get_user_id()
        path = workspace_service.save_file(uid, filename, buf.read())
        total_rows = sum(len(s.get("rows", [])) for s in sheets)
        logger.info("Created spreadsheet: %s (%d sheets, %d rows)", path, len(sheets), total_rows)
        return f"Spreadsheet saved: {path} ({len(sheets)} sheet(s), {total_rows} data rows)"

    except Exception as exc:
        logger.warning("Failed to create spreadsheet: %s", exc, exc_info=True)
        return f"Failed to create spreadsheet: {exc}"


# ---------------------------------------------------------------------------
# PDF (.pdf)
# ---------------------------------------------------------------------------

@tool
def create_pdf(title: str, content_markdown: str) -> str:
    """Create a PDF document from markdown content.

    Args:
        title: Document title (used as filename and header).
        content_markdown: The document content in markdown format.
            Supports: headings, bold, italic, bullet lists, numbered lists, tables.

    Returns: Path to the saved .pdf file in the workspace.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        return (
            "fpdf2 is not installed. Add it to pyproject.toml: "
            "uv add fpdf2"
        )

    try:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 22)
        pdf.cell(0, 15, title, new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(8)

        # Parse and render markdown line by line
        lines = content_markdown.split("\n")

        for line in lines:
            stripped = line.strip()

            if not stripped:
                pdf.ln(4)
                continue

            # Headings
            if stripped.startswith("### "):
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 13)
                pdf.cell(0, 8, stripped[4:], new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
                continue
            if stripped.startswith("## "):
                pdf.ln(5)
                pdf.set_font("Helvetica", "B", 15)
                pdf.cell(0, 9, stripped[3:], new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
                continue
            if stripped.startswith("# "):
                pdf.ln(6)
                pdf.set_font("Helvetica", "B", 18)
                pdf.cell(0, 10, stripped[2:], new_x="LMARGIN", new_y="NEXT")
                pdf.ln(3)
                continue

            # Horizontal rule
            if stripped in ("---", "***", "___"):
                pdf.ln(3)
                pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
                pdf.ln(3)
                continue

            # Bullet lists
            if stripped.startswith("- ") or stripped.startswith("* "):
                pdf.set_font("Helvetica", "", 11)
                text = stripped[2:]
                text = _render_inline_formatting(text)
                pdf.cell(8)  # indent
                pdf.cell(5, 6, "\u2022")
                pdf.multi_cell(0, 6, text)
                continue

            # Numbered lists
            numbered_match = re.match(r"^(\d+)\.\s+(.+)", stripped)
            if numbered_match:
                pdf.set_font("Helvetica", "", 11)
                num = numbered_match.group(1)
                text = _render_inline_formatting(numbered_match.group(2))
                pdf.cell(8)  # indent
                pdf.cell(8, 6, f"{num}.")
                pdf.multi_cell(0, 6, text)
                continue

            # Regular paragraph
            pdf.set_font("Helvetica", "", 11)
            text = _render_inline_formatting(stripped)
            pdf.multi_cell(0, 6, text)

        # Save to bytes buffer then to workspace
        buf = BytesIO()
        pdf.output(buf)
        buf.seek(0)

        filename = f"{_slugify(title)}.pdf"
        uid = _get_user_id()
        path = workspace_service.save_file(uid, filename, buf.read())
        logger.info("Created PDF: %s", path)
        return f"PDF saved: {path}"

    except Exception as exc:
        logger.warning("Failed to create PDF: %s", exc, exc_info=True)
        return f"Failed to create PDF: {exc}"


def _render_inline_formatting(text: str) -> str:
    """Strip markdown inline formatting for plain-text PDF rendering.

    fpdf2 doesn't support rich inline formatting in multi_cell, so we
    strip bold/italic markers and return plain text.
    """
    # Remove bold (**text** or __text__)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"__(.+?)__", r"\1", text)
    # Remove italic (*text* or _text_)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"(?<!\w)_(.+?)_(?!\w)", r"\1", text)
    # Remove inline code (`text`)
    text = re.sub(r"`(.+?)`", r"\1", text)
    # Remove links [text](url) → text
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    return text


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_office_tools() -> list:
    """Return all office document export tools."""
    return [create_presentation, create_spreadsheet, create_pdf]
